# Generated by Django 3.1.2 on 2020-12-01 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_turno'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
    ]
