# Generated by Django 3.1.2 on 2020-12-01 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_turno_medico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='hora',
        ),
        migrations.AddField(
            model_name='turno',
            name='horario',
            field=models.CharField(choices=[('1000', '10:00 hs'), ('1030', '10:30 hs'), ('1100', '11:00 hs'), ('1130', '11:30 hs'), ('1200', '12:00 hs'), ('1230', '12:30 hs'), ('1300', '13:00 hs'), ('1330', '13:30 hs'), ('1400', '14:00 hs'), ('1430', '14:30 hs'), ('1500', '15:00 hs')], default='', max_length=4, verbose_name='Horario de Turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Médico'),
        ),
    ]
