# Generated by Django 3.1.2 on 2020-12-01 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20201201_0414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la categoria')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='Precio')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='img/productos/%4/%m/%d', verbose_name='Imagen')),
                ('stock', models.IntegerField(blank=True, default=1, null=True, verbose_name='Cantidad')),
                ('lado_izquierdo', models.BooleanField(default=False, verbose_name='Izquierdo')),
                ('lado_derecho', models.BooleanField(default=False, verbose_name='Derecho')),
                ('distancia_cerca', models.BooleanField(default=False, verbose_name='Cerca')),
                ('distancia_lejos', models.BooleanField(default=False, verbose_name='Lejos')),
                ('armazon', models.BooleanField(default=False, verbose_name='Armazón')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
    ]
