# Generated by Django 3.1.2 on 2020-12-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_categoria_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='armazon',
            field=models.BooleanField(default=False, verbose_name='Con Armazón'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='distancia_cerca',
            field=models.BooleanField(default=False, verbose_name='Lente de Cerca'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='distancia_lejos',
            field=models.BooleanField(default=False, verbose_name='Lente de Lejos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lado_derecho',
            field=models.BooleanField(default=False, verbose_name='Lente Lado Derecho'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='lado_izquierdo',
            field=models.BooleanField(default=False, verbose_name='Lente Lado Izquierdo'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Cantidad en Stock'),
        ),
    ]
