# Generated by Django 3.1.2 on 2020-12-01 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201201_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Precio')),
                ('tipo_pago', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('T', 'Taller'), ('F', 'Finalizado')], default='P', max_length=1, verbose_name='Estado actual del pedido')),
                ('tipo_de_pago', models.CharField(choices=[('TC', 'Tarjeta de credito'), ('BV', 'Billetera virtual'), ('EF', 'Efectivo'), ('DE', 'Debito')], default='TC', max_length=2, verbose_name='Tipo de pago')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.paciente', verbose_name='Paciente')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.producto')),
            ],
        ),
    ]
