# Generated by Django 3.1.2 on 2020-12-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='precio',
        ),
        migrations.AddField(
            model_name='pedido',
            name='preciototal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=14, null=True, verbose_name='Precio Total'),
        ),
    ]
