# Generated by Django 3.1.2 on 2020-12-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20201201_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallepedido',
            name='subtotal',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=11, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/%Y/%m/%d', verbose_name='Imagen'),
        ),
    ]
